### ISSUE TITLE
Crash in sp2gpl

### ISSUE THREAD

**Issue by goord** [blue-action/ece-postprocess#9] opened 2018-10-12 14:43 UTC
The script crashes with the traceback
```
Traceback (most recent call last):
  File "/nfs/home/users/oord/miniconda2/envs/blueact/bin/ece-postprocess", line 4, in <module>
    __import__('pkg_resources').run_script('ece-postprocess==0.1', 'ece-postprocess')
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/ece_postprocess-0.1-py3.5.egg/EGG-INFO/scripts/ece-postprocess", line 82, in <module>
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/ece_postprocess-0.1-py3.5.egg/ece_postprocess/AMET_land_surface.py", line 105, in __init__
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/ece_postprocess-0.1-py3.5.egg/ece_postprocess/AMET_land_surface.py", line 136, in runPostprocess
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/ece_postprocess-0.1-py3.5.egg/ece_postprocess/AMET_land_surface.py", line 428, in sp2gpl
  File "/nfs/home/users/oord/miniconda2/envs/blueact/lib/python3.5/site-packages/ece_postprocess-0.1-py3.5.egg/ece_postprocess/AMET_land_surface.py", line 428, in <listcomp>
ValueError: invalid literal for int() with base 10: ''
```
Will investigate further

**Comment by goord** [comment] 2018-10-12 14:51
This only occurs when applying the script to the first leg, which contains the ICM{GG,SH}ece3+000000 files btw, so not a showstopper for me

**Comment by rvanharen** [comment] 2018-10-12 15:08
I might have a fix for this one locally, I recall running into the same issue at some point

**Comment by rvanharen** [comment] 2018-11-14 15:29
duplicate of #11

**Closed** 2018-11-14 15:29 UTC
